package models;

import java.time.LocalDateTime;

import javax.inject.Inject;

import play.libs.mailer.Email;
import play.libs.mailer.MailerClient;


/**
 * Class for an autogenerated transaction email in GarageBuddy.
 *
 * @author Taj Gillani
 * @version 1.0.0
 */

public class TransactionEmail {
    @Inject MailerClient mailerClient;
    private final Transaction trans;
    private final LocalDateTime generated;

    /**
     * Creates an Email.
     *
     * @param t The transaction that this email represents.
     */
    public TransactionEmail(final Transaction t) {
        this.trans = t;
        this.generated = LocalDateTime.now();
    }

    /**
     * Prepares and sends an email about the completion of trans
     */

    public void mailOut() {
        // make message parts
    }
}
